name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/
  pull_request:
    branches:
      - main
      - feature/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install Flask  # Install Flask (needed to run Flask app) 

      - name: Run Tests
        run: |
          python -m tests.test_app  # Run the test in tests/test_app.py

      - name: Run Static Analysis
        run: |
          flake8 .  # Run static analysis on the entire project

  automerge:
    needs: build
    runs-on: ubuntu-latest
    if: success()  # Ensure this only runs if the previous job is successful
    steps:
      - name: Enable Auto-Merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ###### this part contains the failure mail job. due to the need of SMTP server, i've commented it.

      #- name: Send Failure Notification (Email)
      #  if: failure()
      #  run: |
      #    curl --request POST \
      #    --url https://api.sendgrid.com/v3/mail/send \
      #    --header 'Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}' \
      #    --header 'Content-Type: application/json' \
      #    --data '{
      #      "personalizations": [{"to": [{"email": "recipient@example.com"}]}],
      #      "from": {"email": "your-email@example.com"},
      #      "subject": "CI/CD Pipeline Failed",
      #      "content": [{"type": "text/plain", "value": "The CI/CD pipeline failed. Please check the logs for details."}]
      #    }'


    